version: "3"

services:
  timeoff:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./db.production.sqlite:/app/db.production.sqlite
      - sqlite-data:/app/db
      - ./config:/app/config

volumes:
  sqlite-data:
