version: "3"

services:
  timeoff:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - sqlite-data:/app/db

volumes:
  sqlite-data:
